### ISSUE TITLE
Error with Example in Documentation

### ISSUE THREAD

**Issue by JeroenSchmidt** [lyft/amundsen#145]
Python: 3.6.7
Docker-Compose: 1.24.1, build 4667896b
OS: Ubuntu 1.24.1, build 4667896b
 
I am running through the example provided in the [documentation](https://github.com/lyft/amundsen/blob/master/docs/installation.md). 

I get an error when I run `python3 example/scripts/sample_data_loader.py`

```
## within the databuilder directory
~/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 229, in perform_request
    raise ConnectionError("N/A", str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7fbe64347860>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fbe64347860>: Failed to establish a new connection: [Errno 111] Connection refused)
```

```
# within the docker compose terminal
WARNING:elasticsearch:GET http://es_amundsen:9200/table_search_index/_search [status:N/A request:0.014s]
amundsensearch      | Traceback (most recent call last):
amundsensearch      |   File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 141, in _new_conn
amundsensearch      |     (self.host, self.port), self.timeout, **extra_kw)
amundsensearch      |   File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 60, in create_connection
amundsensearch      |     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
amundsensearch      |   File "/usr/local/lib/python3.7/socket.py", line 748, in getaddrinfo
amundsensearch      |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
amundsensearch      | socket.gaierror: [Errno -2] Name or service not known
amundsensearch      | 
amundsensearch      | During handling of the above exception, another exception occurred:

```

Within the amundsen UI I can see test_table1 under the popular section of the homepage but nothing shows up if I search for "test".

I can also hit the following URLS:
http://localhost:5000/table_detail/gold/hive/test_schema/test_table1
http://localhost:5000/table_detail/gold/dynamo/test_schema/test_table2

Within the table pages I can see the users and coloumn names but I am unable to see column statistics or preview the data (should this be possible?).

Quering * within neo4j returns:
```
╒════════════════════════════════════╕
│"n"                                 │
╞════════════════════════════════════╡
│{"publisher_last_updated_epoch_ms":1│
│571745584962,"description":"1st test│
│ table","published_tag":"unique_tag"│
│,"key":"hive://gold.test_schema/test│
│_table1/_description"}              │
├────────────────────────────────────┤
│{"publisher_last_updated_epoch_ms":1│
│571745584991,"description":"2nd test│
│ table","published_tag":"unique_tag"│
│,"key":"dynamo://gold.test_schema/te│
│st_table2/_description"}            │
├────────────────────────────────────┤
│{"name":"test_schema","publisher_las│
│t_updated_epoch_ms":1571745585029,"p│
│ublished_tag":"unique_tag","key":"hi│
│ve://gold.test_schema"}             │
├────────────────────────────────────┤
│{"name":"test_schema","publisher_las│
│t_updated_epoch_ms":1571745585042,"p│
│ublished_tag":"unique_tag","key":"dy│
│namo://gold.test_schema"}           │
├────────────────────────────────────┤
│{"name":"test_table1","publisher_las│
│t_updated_epoch_ms":1571745585083,"p│
│ublished_tag":"unique_tag","key":"hi│
│ve://gold.test_schema/test_table1","│
│is_view":false}                     │
├────────────────────────────────────┤
│{"name":"test_table2","publisher_las│
│t_updated_epoch_ms":1571745585097,"p│
│ublished_tag":"unique_tag","key":"dy│
│namo://gold.test_schema/test_table2"│
│,"is_view":false}                   │
├────────────────────────────────────┤
│{"name":"gold","publisher_last_updat│
│ed_epoch_ms":1571745585125,"publishe│
│d_tag":"unique_tag","key":"hive://go│
│ld"}                                │
├────────────────────────────────────┤
│{"name":"gold","publisher_last_updat│
│ed_epoch_ms":1571745585135,"publishe│
│d_tag":"unique_tag","key":"dynamo://│
│gold"}                              │
├────────────────────────────────────┤
│{"name":"hive","publisher_last_updat│
│ed_epoch_ms":1571745585162,"publishe│
│d_tag":"unique_tag","key":"database:│
│//hive"}                            │
├────────────────────────────────────┤
│{"name":"dynamo","publisher_last_upd│
│ated_epoch_ms":1571745585172,"publis│
│hed_tag":"unique_tag","key":"databas│
│e://dynamo"}                        │
├────────────────────────────────────┤
│{"publisher_last_updated_epoch_ms":1│
│571745585788,"description":"col1 des│
│cription","published_tag":"unique_ta│
│g","key":"hive://gold.test_schema/te│
│st_table1/col1/_description"}       │
├────────────────────────────────────┤
│{"publisher_last_updated_epoch_ms":1│
│571745585794,"description":"col2 des│
│cription","published_tag":"unique_ta│
│g","key":"hive://gold.test_schema/te│
│st_table1/col2/_description"}       │
├────────────────────────────────────┤
│{"publisher_last_updated_epoch_ms":1│
│571745585800,"description":"col3 des│
│cription","published_tag":"unique_ta│
│g","key":"hive://gold.test_schema/te│
│st_table1/col3/_description"}       │
├────────────────────────────────────┤
│{"publisher_last_updated_epoch_ms":1│
│571745585808,"description":"col4 des│
│cription","published_tag":"unique_ta│
│g","key":"hive://gold.test_schema/te│
│st_table1/col4/_description"}       │
├────────────────────────────────────┤
│{"publisher_last_updated_epoch_ms":1│
│571745585816,"description":"col1 des│
│cription","published_tag":"unique_ta│
│g","key":"dynamo://gold.test_schema/│
│test_table2/col1/_description"}     │
├────────────────────────────────────┤
│{"publisher_last_updated_epoch_ms":1│
│571745585824,"description":"col2 des│
│cription","published_tag":"unique_ta│
│g","key":"dynamo://gold.test_schema/│
│test_table2/col2/_description"}     │
├────────────────────────────────────┤
│{"publisher_last_updated_epoch_ms":1│
│571745585833,"description":"col3 des│
│cription","published_tag":"unique_ta│
│g","key":"dynamo://gold.test_schema/│
│test_table2/col3/_description"}     │
├────────────────────────────────────┤
│{"publisher_last_updated_epoch_ms":1│
│571745585840,"description":"col4 des│
│cription","published_tag":"unique_ta│
│g","key":"dynamo://gold.test_schema/│
│test_table2/col4/_description"}     │
├────────────────────────────────────┤
│{"name":"col1","publisher_last_updat│
│ed_epoch_ms":1571745585862,"publishe│
│d_tag":"unique_tag","type":"string",│
│"sort_order":"1","key":"hive://gold.│
│test_schema/test_table1/col1"}      │
├────────────────────────────────────┤
│{"name":"col2","publisher_last_updat│
│ed_epoch_ms":1571745585869,"publishe│
│d_tag":"unique_tag","type":"string",│
│"sort_order":"2","key":"hive://gold.│
│test_schema/test_table1/col2"}      │
├────────────────────────────────────┤
│{"name":"col3","publisher_last_updat│
│ed_epoch_ms":1571745585877,"publishe│
│d_tag":"unique_tag","type":"string",│
│"sort_order":"3","key":"hive://gold.│
│test_schema/test_table1/col3"}      │
├────────────────────────────────────┤
│{"name":"col4","publisher_last_updat│
│ed_epoch_ms":1571745585883,"publishe│
│d_tag":"unique_tag","type":"string",│
│"sort_order":"4","key":"hive://gold.│
│test_schema/test_table1/col4"}      │
├────────────────────────────────────┤
│{"name":"col1","publisher_last_updat│
│ed_epoch_ms":1571745585890,"publishe│
│d_tag":"unique_tag","type":"string",│
│"sort_order":"1","key":"dynamo://gol│
│d.test_schema/test_table2/col1"}    │
├────────────────────────────────────┤
│{"name":"col2","publisher_last_updat│
│ed_epoch_ms":1571745585897,"publishe│
│d_tag":"unique_tag","type":"string",│
│"sort_order":"2","key":"dynamo://gol│
│d.test_schema/test_table2/col2"}    │
├────────────────────────────────────┤
│{"name":"col3","publisher_last_updat│
│ed_epoch_ms":1571745585904,"publishe│
│d_tag":"unique_tag","type":"string",│
│"sort_order":"3","key":"dynamo://gol│
│d.test_schema/test_table2/col3"}    │
└────────────────────────────────────┘
```

**Comment by jornh** [comment]
So, looks like you Neo4j container is running as it should but your Elasticsearch isn’t 

Does https://github.com/lyft/amundsen/blob/master/docs/installation.md#troubleshooting help in your environment 

If not, what does the docker logs reveal?

**Comment by jornh** [comment]
@JeroenSchmidt were you able to investigate further on this?

On re-reading your error post I now see that you infact _did_ post docker compose output! (on first response I overlooked your `# within the docker compose terminal` comment, and read it as output from the databuilder run which can look quite similar, sorry) I added an edit in my https://github.com/lyft/amundsen/issues/145#issuecomment-545073479 above.

To clarify and hopefully get Quickstart working for you I would expect that the output of the `es_amundsen` container would reveal some kind of error output/crash info.

An alternative might be to try running on another machine...

**Comment by feng-tao** [comment]
@JeroenSchmidt let us know if the issue still persists.

**Comment by JeroenSchmidt** [comment]
@feng-tao I haven't had the time again to look into it better. I will try get back to you next week with more information.

**Comment by mishranaveen** [comment]
max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144] ..... from link shared by @jornh fixed my problem .
