### ISSUE TITLE
Sample snowflake data loader getting hung

### ISSUE THREAD

**Issue by abhishenator** [lyft/amundsen#153]
Using following command and it gets hung. Pressing Ctrl+C gives me stacktrace telling what function is being blocked:

```
python example/scripts/sample_snowflake_data_loader.py

^CTraceback (most recent call last):
  File "example/scripts/sample_snowflake_data_loader.py", line 75, in <module>
    job.launch()
  File "/Users/abhishek.arora/data-discovery/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/amundsen_databuilder-1.4.8-py3.6.egg/databuilder/job/job.py", line 74, in launch
  File "/Users/abhishek.arora/data-discovery/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/amundsen_databuilder-1.4.8-py3.6.egg/databuilder/publisher/base_publisher.py", line 34, in publish
  File "/Users/abhishek.arora/data-discovery/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/amundsen_databuilder-1.4.8-py3.6.egg/databuilder/publisher/neo4j_csv_publisher.py", line 197, in publish_impl
  File "/Users/abhishek.arora/data-discovery/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/amundsen_databuilder-1.4.8-py3.6.egg/databuilder/publisher/neo4j_csv_publisher.py", line 329, in _publish_relation
  File "/Users/abhishek.arora/data-discovery/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/amundsen_databuilder-1.4.8-py3.6.egg/databuilder/publisher/neo4j_csv_publisher.py", line 432, in _execute_statement
  File "/Users/abhishek.arora/data-discovery/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/neo4j/__init__.py", line 792, in commit
    self.close()
  File "/Users/abhishek.arora/data-discovery/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/neo4j/__init__.py", line 815, in close
    self.sync()
  File "/Users/abhishek.arora/data-discovery/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/neo4j/__init__.py", line 780, in sync
    self.session.sync()
  File "/Users/abhishek.arora/data-discovery/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/neo4j/__init__.py", line 531, in sync
    detail_count, _ = self._connection.sync()
  File "/Users/abhishek.arora/data-discovery/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/neobolt/direct.py", line 531, in sync
    detail_delta, summary_delta = self.fetch()
  File "/Users/abhishek.arora/data-discovery/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/neobolt/direct.py", line 422, in fetch
    return self._fetch()
  File "/Users/abhishek.arora/data-discovery/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/neobolt/direct.py", line 443, in _fetch
    self._receive()
  File "/Users/abhishek.arora/data-discovery/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/neobolt/direct.py", line 493, in _receive
    raise KeyboardInterrupt()
KeyboardInterrupt
```

Also, there was a minor bug in the import: `from urllib import unquote_plus` must be `from urllib.parse import unquote_plus`

**Comment by abhishenator** [comment]
Actually, I had 2500 tables. It just took a long time and it eventually finished. Closing this out.

**Comment by jornh** [comment]
Good to have logged here for “knowledge base”.

Just for the record - with 2500 tables (and how many columns) roughly how long did it take?

Also - would be great if you could push a PR with your Py 3 import issue!
