### ISSUE TITLE
Could not ingest sample data

### ISSUE THREAD

**Issue by TrungTri** [lyft/amundsen#391]
Hi,

I want to ingest sample data to amundsen. 
e5c91afcedff        amundsendev/amundsen-frontend:1.2.0   "python3 amundsen_ap…"   57 minutes ago      Up 57 minutes       0.0.0.0:5000->5000/tcp                                     amundsenfrontend
33e69e617a07        amundsendev/amundsen-metadata:1.1.5   "python3 metadata_se…"   57 minutes ago      Up 57 minutes       0.0.0.0:5002->5000/tcp                                     amundsenmetadata
adb749cf0637        amundsendev/amundsen-search:1.4.2     "python3 search_serv…"   58 minutes ago      Up 57 minutes       0.0.0.0:5001->5000/tcp                                     amundsensearch
7e743fc8989e        wbaa/rokku-dev-apache-atlas:0.1.4     "sh -c /entrypoint.sh"   58 minutes ago      Up 57 minutes       0.0.0.0:21000->21000/tcp                                   atlas_amundsen
b20d00135eb4        neo4j:3.3.0                           "/docker-entrypoint.…"   59 minutes ago      Up 59 minutes       0.0.0.0:7474->7474/tcp, 7473/tcp, 0.0.0.0:7687->7687/tcp   neo4j_amundsen
514db4947b47        mysql:5.7                             "docker-entrypoint.s…"   36 hours ago        Up 8 hours          0.0.0.0:3306->3306/tcp, 33060/tcp  
but when I run 
python3 example/scripts/sample_data_loader.py
It could not connect to elasticsearch. Please help me. Thank you

WARNING:elasticsearch:PUT http://localhost:9200/tablesfe93e222-9538-4eff-b319-dd1be7cc3d1b [status:N/A request:0.001s]
Traceback (most recent call last):
  File "/home/trung/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/trung/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/trung/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/trung/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 212, in perform_request
    method, url, body, retries=Retry(False), headers=request_headers, **kw
  File "/home/trung/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/trung/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 379, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/trung/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/home/trung/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/trung/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/home/trung/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/home/trung/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f972b06cac8>: Failed to establish a new connection: [Errno 111] Connection refused
WARNING:elasticsearch:PUT http://localhost:9200/tablesfe93e222-9538-4eff-b319-dd1be7cc3d1b [status:N/A request:0.001s]
Traceback (most recent call last):
  File "/home/trung/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/trung/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/trung/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by jornh** [comment]
Looks like you are using the Atlas backend - indicated by:

```
7e743fc8989e wbaa/rokku-dev-apache-atlas:0.1.4 "sh -c /entrypoint.sh" 58 minutes ago Up 57 minutes 0.0.0.0:21000->21000/tcp atlas_amundsen
```

That backed does not work with the Databuilder for ingesting sample data but has its own sample data built in. Also noted with a comment in the Quickstart instructions.

**Comment by TrungTri** [comment]
Hi John. I ran atlats but there is no testing data in Amundsend. So that 's why I tried to ingest data using Databuilder. If I shut Atlas down and run the python script again, it would cause the same errors. I think there is some wrong config in making connection to elastic in python scripts

**Comment by jornh** [comment]
If there is no testing data in Amundsen, then something failed during Atlas startup. If you are not there already then join the Amundsen Slack workspace - and see [this Question](https://amundsenworkspace.slack.com/archives/CHQERT0D7/p1586854760094100) and [this answer thread](https://amundsenworkspace.slack.com/archives/CHQERT0D7/p1586949647118500?thread_ts=1586891411.100900&cid=CHQERT0D7) from the #troubleshooting channel for. Other things to try: Have you checked the Atlas container logs during startup for errors and that it runs to completion? Can you navigate to the Atlas UI?

It won't work with Databuilder and Atlas. See [this recent Atlas slide](https://docs.google.com/presentation/d/1FixTTNd1dt_f3PAKhL1KLOeOLsIQq0iFvQA6qlpjIg0/present?token=AC4w5VjG3vImQ-deQc3uddTihvTlii7GFw%3A1587200387617&includes_info_params=1&eisi=CKKDq5rO8egCFRe9Hwod2g0PNQ#slide=id.g7ddabb3573_0_241) - and check the animation with `->` then `<-` arrow keys to see the difference with Atlas and Neo4j/Elasticsearch backends. It shows that Atlas replaces all of Neo4j, Elasticsearch and Databuilder. Since there's no Elasticsearch that's why Databuilder can't connect to ElasticSearch.

**Comment by jornh** [comment]
@TrungTri what’s the status on your end with this? Does this resolve the issue?

As it stands I think you got answers to your questions and I don’t see anything actionable for the Amundsen project here.

**Comment by TrungTri** [comment]
Thank you so much. It is much clearer with your slide. it is due to I start the two services the same time both amundsen and amundsen-atlas
Thank you very much. I am having a look at it at the moment
