### ISSUE TITLE
FrontEnd Installation fails when OIDC is enabled

### ISSUE THREAD

**Issue by diegoep** [lyft/amundsen#527]
I'm trying to install Amundsen via the provided helm charts, but the FrontEnd module is failing when ODIC is enabled. It's returning the following:
`Registering post_exec action_log entry_point: logging_action_log = amundsen_application.log.action_log_callback:logging_action_log
Traceback (most recent call last):
  File "amundsen_application/wsgi.py", line 2, in <module>
    from amundsen_application import create_app
  File "/usr/local/lib/python3.7/site-packages/amundsen_frontend-2.1.1-py3.7.egg/amundsen_application/__init__.py", line 26, in <module>
    module = importlib.import_module(moduleName)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'flaskoidc'`

## Expected Behavior
Application should went up and be ready to receive requests.

## Current Behavior
it's needed to disable the property oidcEnabled to be possible to run the frontEnd application.

## Possible Solution

Flask-OIDC library should be added to the requirements.txt

**Comment by diegoep** [comment]
I've just figured out that there's a different image to be used when oidc is enabled.
https://hub.docker.com/r/amundsendev/amundsen-frontend-oidc
