### ISSUE TITLE
print(f'Using requested Flask module {FLASK_APP_MODULE_NAME} ' SyntaxError: invalid syntax**

### ISSUE THREAD

**Issue by satishjb** [lyft/amundsen#79]
python3 search_service/search_wsgi.py
Traceback (most recent call last):
  File "search_service/search_wsgi.py", line 3, in <module>
    from search_service import create_app
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1171, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1147, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1128, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 565, in spec_from_file_location
  File "/home/satish/projects/amundsen/amundsensearchlibrary/venv/lib/python3.5/site-**packages/amundsen_search-1.1.3-py3.5.egg/search_service/__init__.py", line 37
    print(f'Using requested Flask module {FLASK_APP_MODULE_NAME} '
SyntaxError: invalid syntax**

**Comment by jornh** [comment]
Real sorry about the current inconsistency for python version requirements across repos 

For the search service `setup.py` states python 3.6 as minimum requirement (but there’s no badge/text mention on that in the README.. Also I think currently the Travis CI runs with 3.6 across the board (apart from Databuilder which Lyft has a need to hold back on 2.7). To top it off the dockerfiles use 3.7!

If python 3.5 is a real need for you, you can convert from 3.6 f-string to the old 3.5 .format syntax. Otherwise I’d recommend moving to 3.6 or 3.7.

Personally I’m on 3.6/3.7 and I actually prefer the new leaner f-string syntax etc, and with containers virtualenv etc. see little reason for a young project as Amundsen to keep to much old baggage. @feng-tao @jinhyukchang any “official” opinion on this?
